/*
 * Taxi Service API
 * API para el servicio de taxis
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse400
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-16T22:23:21.937Z")
public class InlineResponse400 {
  @SerializedName("mensaje")
  private String mensaje = null;

  @SerializedName("error")
  private String error = null;

  public InlineResponse400 mensaje(String mensaje) {
    this.mensaje = mensaje;
    return this;
  }

   /**
   * Mensaje de error
   * @return mensaje
  **/
  @ApiModelProperty(example = "No se ha podido registrar al cliente", value = "Mensaje de error")
  public String getMensaje() {
    return mensaje;
  }

  public void setMensaje(String mensaje) {
    this.mensaje = mensaje;
  }

  public InlineResponse400 error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Detalles del error
   * @return error
  **/
  @ApiModelProperty(example = "xxxxx", value = "Detalles del error")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse400 inlineResponse400 = (InlineResponse400) o;
    return Objects.equals(this.mensaje, inlineResponse400.mensaje) &&
        Objects.equals(this.error, inlineResponse400.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensaje, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse400 {\n");
    
    sb.append("    mensaje: ").append(toIndentedString(mensaje)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

