/*
 * Taxi Service API
 * API para el servicio de taxis
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.Cliente;
import io.swagger.client.model.InlineResponse201;
import io.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Registrar un nuevo cliente
     *
     * Endpoint para que los clientes se registren en el servicio de taxis.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clientesPostTest() throws Exception {
        Cliente cliente = null;
        InlineResponse201 response = api.clientesPost(cliente);

        // TODO: test validations
    }
    
}
